services:

  proxy:
    image: nginx:alpine
    container_name: onyks-bloodstone-proxy
    ports:
      - "80:80"
    volumes:
        - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - frontend
      - svn
      - backend

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ${CONFIG_FILE:-.env}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ${SVN_DATA_PATH}/${SVN_REPO_NAME}:/local_svn
      - ${DATASHEET_UPLOAD_PATH}:/uploads


  database:
    image: postgres:16-alpine
    container_name: onyks-bloodstone-database
    restart: unless-stopped
    env_file: ${CONFIG_FILE:-.env}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  svn:
    build: ./svn
    restart: unless-stopped
    env_file: ${CONFIG_FILE:-.env}
    ports:
      - "${SVN_PORT}:443"
    volumes:
      - ${SVN_DATA_PATH}:/var/svn
    depends_on:
      - database